### ISSUE TITLE
Clean Up Signs

### ISSUE THREAD

**Issue by mide** [mide/minecraft-overviewer#61]
Ideas:
- [x]  ~Allow filter to match case insensitive (`-- RENDER --` or `-- render --` or `-- Render --` all match)~ _Will not implement per #63_
- [x] Strip empty lines from displaying (maybe only from edges, not between lines) #68
- [x] Code cleanup, maybe some kind of `map` and `filter` to process the signs? #63
- [ ] Figure out how to horizontally center sign test within render.
- [x] Figure out how to break the sign filter code into multiple functions (see #68)

**Comment by mide** [comment]
Case insensitive and filters done in #63

**Comment by mide** [comment]
Per discussions in #63, we won't have case insensitive.

**Comment by magneticflux-** [comment]
Also to consider: centering the signs' text and preserving blank lines in the sign. For centering theoretically you could add `<br /> <center>` as the joiner, but that's not HTML5 😞. I don't know what to do about blank lines. Maybe just remove them if they're empty after a `.strip()`?

This is what signs currently look like on my map:
![image](https://user-images.githubusercontent.com/9124288/78743797-4c5aee80-7925-11ea-9d8e-977bfbcdf57e.png)


Additionally, if there are blank lines at the beginning of the sign, they appear in the text. Blank lines at the end of the sign don't, so all signs that are vertically centered in-game look top-heavy in the render.

**Comment by mide** [comment]
Yeah, this needs some work for sure. In the meantime you can switch back to the previous behavior and use a space `" "` as the joiner.

I agree 💯 with you though, and I hope to fix this.

**Comment by mide** [comment]
@magneticflux- I propose #68 to deal with the spacing (the signs being top heavy)

**Comment by mide** [comment]
> Figure out how to break the sign filter code into multiple functions (see https://github.com/mide/minecraft-overviewer/pull/68)

Given the upstream project is [no longer maintained](https://github.com/overviewer/Minecraft-Overviewer/commit/13c1bddaf65dfaaf6c4c7a396c94db75bed4c089), and there is an open issue for this, I will mark this task as complete, as `wontfix`.
